//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyPepita.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyPepita.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\AuthorizationKeys.xml.
        /// </summary>
        internal static string ADDRESS_KEYS {
            get {
                return ResourceManager.GetString("ADDRESS_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\Tweets.xml.
        /// </summary>
        internal static string ADDRESS_TWEETS {
            get {
                return ResourceManager.GetString("ADDRESS_TWEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\UpdateControls.xml.
        /// </summary>
        internal static string ADDRESS_UPDATECONTROLS {
            get {
                return ResourceManager.GetString("ADDRESS_UPDATECONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastGoodMorningTweet.
        /// </summary>
        internal static string IDENTIFIER_LAST_GM_TWEET {
            get {
                return ResourceManager.GetString("IDENTIFIER_LAST_GM_TWEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastTweet.
        /// </summary>
        internal static string IDENTIFIER_LAST_TWEET {
            get {
                return ResourceManager.GetString("IDENTIFIER_LAST_TWEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oi! Meu nome é Olivia e eu criei esse bot porque gostaria de receber todo dia uma mensagem da @pepitaofc ao acordar! Meu Twitter e GitHub são @oliviamattiazzo, me segue lá! ✨.
        /// </summary>
        internal static string Resposta_MsgCreditos {
            get {
                return ResourceManager.GetString("Resposta_MsgCreditos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá! Não entendi o seu pedido. Os comandos que retornam mensagens são: &quot;Bom dia&quot;, &quot;Novidades&quot; e &quot;Créditos&quot;. Tente novamente! ✨.
        /// </summary>
        internal static string Resposta_MsgPadrao {
            get {
                return ResourceManager.GetString("Resposta_MsgPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja bem viado ao Hey, Pepita bot! Os comandos que retornam mensagens são: &quot;Bom dia&quot;, &quot;Novidades&quot; e &quot;Créditos&quot;. Fique à vontade! ✨.
        /// </summary>
        internal static string Resposta_MsgWelcome {
            get {
                return ResourceManager.GetString("Resposta_MsgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desej, feira, segunda, terça, terca, quarta, quinta, sexta, sábado, sabado, domingo, família, familia, todos, bom dia, boa tarde, coisas boas, melhor, semana, nossas vidas, nossa vida.
        /// </summary>
        internal static string WORDS_GOOD_MORNING {
            get {
                return ResourceManager.GetString("WORDS_GOOD_MORNING", resourceCulture);
            }
        }
    }
}
